{
 "title": "DORA Details - Change Failure Rate",
 "tags": [ "DORA" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "select distinct name from projects"
   },
   {
    "name": "dora_report",
    "label": "DORA Report",
    "query": "select dora_report from dora_benchmarks"
   },
   {
    "name": "title_value",
    "label": "TitleValue",
    "query": "SELECT \n  CASE \n    WHEN dora_report = '2023' THEN \"Failed Deployment Recovery Time\"\n    WHEN dora_report = '2021' THEN \"Median Time to Restore Service\"\n    ELSE NULL \n  END AS title_value\nFROM dora_benchmarks\nWHERE dora_report = '${dora_report:raw}'"
   },
   { "name": "author_type", "label": "Author Type", "query": "Human : 0, Bot : 1" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard shows the details about [Change Failure Rate](https://devlake.apache.org/docs/Metrics/CFR) in DORA."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "1. Change Failure Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Metric 3: change failure rate\nwith _deployments as (\n  -- When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date.\n  SELECT\n    cdc.cicd_deployment_id as deployment_id,\n    max(cdc.finished_date) as deployment_finished_date\n  FROM\n    cicd_deployment_commits cdc\n    JOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id\n    JOIN project_pr_metrics ppm on cdc.id = ppm.deployment_commit_id\n    and pm.`table` = 'cicd_scopes'\n    and (ppm.is_authored_by_bot is null or ppm.is_authored_by_bot in (${author_type}))\n  WHERE\n    pm.project_name in (${project})\n    and cdc.result = 'SUCCESS'\n    and cdc.environment = 'PRODUCTION'\n  GROUP BY\n    1\n  HAVING\n    $__timeFilter(max(cdc.finished_date))\n),\n_failure_caused_by_deployments as (\n  -- calculate the number of incidents caused by each deployment\n  SELECT\n    d.deployment_id,\n    d.deployment_finished_date,\n    count(distinct i.id) as has_incident\n  FROM\n    _deployments d\n    left join project_incident_deployment_relationships pim on d.deployment_id = pim.deployment_id\n    left join incidents i on pim.id = i.id\n  GROUP BY\n    1,\n    2\n)\nSELECT\n  sum(has_incident) / count(deployment_id) as \"change_failure_rate\"\nFROM\n  _failure_caused_by_deployments"
    }
   ]
  },
  {
   "title": "2. Deployments that have caused incidents(failure)",
   "type": "table",
   "gridPos": { "h": 17, "w": 20, "x": 4, "y": 2 },
   "targets": [
    {
     "rawSql": "-- Metric 3: change failure rate\nwith _deployments as (\n-- When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date.\n\tSELECT\n\t\tcdc.cicd_deployment_id as deployment_id,\n\t\tmax(cdc.finished_date) as deployment_finished_date\n\tFROM \n\t\tcicd_deployment_commits cdc\n\t\tJOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id and pm.`table` = 'cicd_scopes'\n\t\tJOIN project_pr_metrics ppm on cdc.id = ppm.deployment_commit_id\n\n\tWHERE\n\t\tpm.project_name in (${project})\n\t\tand cdc.result = 'SUCCESS'\n\t\tand cdc.environment = 'PRODUCTION'\n\t\tand (ppm.is_authored_by_bot is null or ppm.is_authored_by_bot in (${author_type}))\n\tGROUP BY 1\n\tHAVING $__timeFilter(max(cdc.finished_date))\n),\n\n_failure_caused_by_deployments as (\n-- calculate the number of incidents caused by each deployment\n\tSELECT\n\t\td.deployment_id as \"deployment_id\",\n\t\td.deployment_finished_date,\n\t\tpim.id as incident_id,\n\t\ti.title,\n\t\ti.url,\n\t\ti.url as \"metric_hidden\",\n\t\ti.created_date\n\t\t-- i.resolution_date,\n\tFROM\n\t\t_deployments d\n\t\tleft join project_incident_deployment_relationships pim on d.deployment_id = pim.deployment_id\n\t\tleft join issues i on pim.id = i.id\n\tWHERE pim.id is not null\n\tORDER BY 2\n)\n\nselect * \nFROM _failure_caused_by_deployments\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Metric 3: change failure rate\nwith _deployments as (\n  -- When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date.\n  SELECT\n    cdc.cicd_deployment_id as deployment_id,\n    max(cdc.finished_date) as deployment_finished_date\n  FROM\n    cicd_deployment_commits cdc\n    JOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id\n    JOIN project_pr_metrics ppm on cdc.id = ppm.deployment_commit_id\n    and pm.`table` = 'cicd_scopes'\n  WHERE\n    pm.project_name in (${project})\n    and cdc.result = 'SUCCESS'\n    and cdc.environment = 'PRODUCTION'\n    and (ppm.is_authored_by_bot is null or ppm.is_authored_by_bot in (${author_type}))\n  GROUP BY\n    1\n  HAVING\n    $__timeFilter(max(cdc.finished_date))\n),\n_failure_caused_by_deployments as (\n  -- calculate the number of incidents caused by each deployment\n  SELECT\n    d.deployment_id,\n    d.deployment_finished_date,\n    count(distinct i.id) as has_incident\n  FROM\n    _deployments d\n    left join project_incident_deployment_relationships pim on d.deployment_id = pim.deployment_id\n    left join incidents i on pim.id = i.id\n  GROUP BY\n    1,\n    2\n)\nSELECT\n  sum(has_incident) as \"incident count\",\n  count(deployment_id) as \"deployment count\"\nFROM\n  _failure_caused_by_deployments"
    }
   ]
  },
  {
   "title": "3. Deployment and incidents timeline",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "with _deployments as(\n  select\n    distinct d.cicd_deployment_id as deployment_id,\n    d.result,\n    d.environment,\n    d.finished_date,\n    d.cicd_scope_id,\n    pm.project_name\n  from\n    cicd_deployment_commits d\n    join project_mapping pm on d.cicd_scope_id = pm.row_id\n    join project_pr_metrics ppm on d.id = ppm.deployment_commit_id\n    and pm.`table` = 'cicd_scopes'\n  where\n    -- only result needs to specified, not envioronment\n    d.result = 'SUCCESS' -- choose your project_name\n    and pm.project_name in ($project)\n    and (ppm.is_authored_by_bot is null or ppm.is_authored_by_bot in (${author_type}))\n    and $__timeFilter(d.finished_date)\n),\n_incidents as(\n  select\n    distinct i.id as issue_id,\n    i.created_date,\n    pm.project_name\n  from\n    incidents i\n    join project_mapping pm on i.scope_id = pm.row_id\n    and i.`table` = pm.`table`\n  where\n    -- choose your project_name\n    pm.project_name in ($project)\n    and $__timeFilter(i.created_date)\n)\nselect\n  finished_date as 'Time (Ascending)',\n  deployment_id as 'Entity ID',\n  'DEPLOYMENT' as 'Entity Type (Deployment/Incident)'\nfrom\n  _deployments\nunion\nselect\n  created_date as 'Time (Ascending)',\n  issue_id as 'Entity ID',\n  'INCIDENT' as 'Entity Type (Deployment/Incident)'\nfrom\n  _incidents\norder by\n  1"
    }
   ]
  }
 ]
}